name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake set-up
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .
    - name: make
      run: cmake --build .
    - uses: actions/upload-artifact@v2
      with:
        name: libsrtnet_osx
        path: ./libsrtnet.a
    - uses: actions/upload-artifact@v2
      with:
        name: libsrt_osx
        path: ./srt/libsrt.a
