name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake set-up
      run: |
        export env.OPENSSL_ROOT_DIR=$(brew --prefix openssl)
        export env.OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
        export env.OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
        cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: cmake --build .
    - uses: actions/upload-artifact@v2
      with:
        name: libsrtnet_osx
        path: ./libsrtnet.a
    - uses: actions/upload-artifact@v2
      with:
        name: libsrt_osx
        path: ./srt/libsrt.a
